scripts: test out new args for remote

diff --git a/scripts/init-repo-mirror b/scripts/init-repo-mirror
--- a/scripts/init-repo-mirror
+++ b/scripts/init-repo-mirror
@@ -48,5 +48,5 @@ fi
 if ${REMOTES}; then
 	echo "Configuring Remotes"
 	git remote remove github &>/dev/null
-	git remote add github git@github.com:gentoo/gentoo-mate.git || die "Failed to configure remotes"
+	git remote add --mirror=push github git@github.com:gentoo/gentoo-mate.git || die "Failed to configure remotes"
 fi
