scripts: init-repo-mirror update uri, remote handling

diff --git a/scripts/init-repo-mirror b/scripts/init-repo-mirror
--- a/scripts/init-repo-mirror
+++ b/scripts/init-repo-mirror
@@ -47,5 +47,6 @@ fi
 
 if ${REMOTES}; then
 	echo "Configuring Remotes"
-	git add remote github https://github.com/gentoo/gentoo-mate/ || die "Failed to configure remotes"
+	git remote remove github &>/dev/null
+	git remote add github git@github.com:gentoo/gentoo-mate.git || die "Failed to configure remotes"
 fi
